import { describe, it, expect } from 'vitest';
import { COLLECTION_GROUPS } from '../src/paths/collection-groups';
import { USER_SUBCOLLECTIONS, NESTED_SUBCOLLECTIONS } from '../src/paths/collections';

describe('COLLECTION_GROUPS', () => {
  it('PROFILE_CRAFT_SKILLS maps to USER_SUBCOLLECTIONS.PROFILE_CRAFT_SKILLS', () => {
    expect(COLLECTION_GROUPS.PROFILE_CRAFT_SKILLS).toBe(USER_SUBCOLLECTIONS.PROFILE_CRAFT_SKILLS);
  });

  it('SOCIAL_POSTS maps to NESTED_SUBCOLLECTIONS.SOCIAL_POSTS', () => {
    expect(COLLECTION_GROUPS.SOCIAL_POSTS).toBe(NESTED_SUBCOLLECTIONS.SOCIAL_POSTS);
  });

  it('TALE_CHAPTERS maps to NESTED_SUBCOLLECTIONS.TALE_CHAPTERS', () => {
    expect(COLLECTION_GROUPS.TALE_CHAPTERS).toBe(NESTED_SUBCOLLECTIONS.TALE_CHAPTERS);
  });

  it('TUNE_TRACKS maps to NESTED_SUBCOLLECTIONS.TUNE_TRACKS', () => {
    expect(COLLECTION_GROUPS.TUNE_TRACKS).toBe(NESTED_SUBCOLLECTIONS.TUNE_TRACKS);
  });

  it('TELEVISION_EPISODES maps to NESTED_SUBCOLLECTIONS.TELEVISION_EPISODES', () => {
    expect(COLLECTION_GROUPS.TELEVISION_EPISODES).toBe(NESTED_SUBCOLLECTIONS.TELEVISION_EPISODES);
  });

  it('GUILD_CHAT_MESSAGES maps to NESTED_SUBCOLLECTIONS.GUILD_CHAT_MESSAGES', () => {
    expect(COLLECTION_GROUPS.GUILD_CHAT_MESSAGES).toBe(NESTED_SUBCOLLECTIONS.GUILD_CHAT_MESSAGES);
  });

  it('COMMISSION_PROPOSALS maps to NESTED_SUBCOLLECTIONS.COMMISSION_PROPOSALS', () => {
    expect(COLLECTION_GROUPS.COMMISSION_PROPOSALS).toBe(NESTED_SUBCOLLECTIONS.COMMISSION_PROPOSALS);
  });

  it('AUDITION_ENTRIES maps to NESTED_SUBCOLLECTIONS.AUDITION_ENTRIES', () => {
    expect(COLLECTION_GROUPS.AUDITION_ENTRIES).toBe(NESTED_SUBCOLLECTIONS.AUDITION_ENTRIES);
  });

  it('CONVERSATION_MESSAGES maps to NESTED_SUBCOLLECTIONS.CONVERSATION_MESSAGES', () => {
    expect(COLLECTION_GROUPS.CONVERSATION_MESSAGES).toBe(NESTED_SUBCOLLECTIONS.CONVERSATION_MESSAGES);
  });

  it('INVITE_MESSAGES maps to NESTED_SUBCOLLECTIONS.INVITE_MESSAGES', () => {
    expect(COLLECTION_GROUPS.INVITE_MESSAGES).toBe(NESTED_SUBCOLLECTIONS.INVITE_MESSAGES);
  });

  it('TAGGED_CRAFT_SKILLS maps to NESTED_SUBCOLLECTIONS.TAGGED_CRAFT_SKILLS', () => {
    expect(COLLECTION_GROUPS.TAGGED_CRAFT_SKILLS).toBe(NESTED_SUBCOLLECTIONS.TAGGED_CRAFT_SKILLS);
  });

  it('USER_SUGGESTIONS maps to NESTED_SUBCOLLECTIONS.USER_SUGGESTIONS', () => {
    expect(COLLECTION_GROUPS.USER_SUGGESTIONS).toBe(NESTED_SUBCOLLECTIONS.USER_SUGGESTIONS);
  });

  it('has all expected keys', () => {
    const expectedKeys = [
      'PROFILE_CRAFT_SKILLS',
      'SOCIAL_POSTS',
      'TALE_CHAPTERS',
      'TUNE_TRACKS',
      'TELEVISION_EPISODES',
      'GUILD_CHAT_MESSAGES',
      'COMMISSION_PROPOSALS',
      'AUDITION_ENTRIES',
      'CONVERSATION_MESSAGES',
      'INVITE_MESSAGES',
      'TAGGED_CRAFT_SKILLS',
      'USER_SUGGESTIONS',
    ];
    for (const key of expectedKeys) {
      expect(COLLECTION_GROUPS).toHaveProperty(key);
    }
  });
});

