import { describe, it, expect } from 'vitest';
import { COLLECTION_GROUPS } from '../src/paths/collection-groups';
import { USER_SUBCOLLECTIONS, NESTED_SUBCOLLECTIONS } from '../src/paths/collections';

describe('COLLECTION_GROUPS', () => {
  it('PROFILE_SKILLS maps to USER_SUBCOLLECTIONS.PROFILE_SKILLS', () => {
    expect(COLLECTION_GROUPS.PROFILE_SKILLS).toBe(USER_SUBCOLLECTIONS.PROFILE_SKILLS);
  });

  it('SOCIAL_POSTS maps to NESTED_SUBCOLLECTIONS.SOCIAL_POSTS', () => {
    expect(COLLECTION_GROUPS.SOCIAL_POSTS).toBe(NESTED_SUBCOLLECTIONS.SOCIAL_POSTS);
  });

  it('LIBRARY_ITEMS maps to NESTED_SUBCOLLECTIONS.LIBRARY_ITEMS', () => {
    expect(COLLECTION_GROUPS.LIBRARY_ITEMS).toBe(NESTED_SUBCOLLECTIONS.LIBRARY_ITEMS);
  });

  it('TALE_CHAPTERS maps to NESTED_SUBCOLLECTIONS.TALE_CHAPTERS', () => {
    expect(COLLECTION_GROUPS.TALE_CHAPTERS).toBe(NESTED_SUBCOLLECTIONS.TALE_CHAPTERS);
  });

  it('TUNE_SONGS maps to NESTED_SUBCOLLECTIONS.TUNE_SONGS', () => {
    expect(COLLECTION_GROUPS.TUNE_SONGS).toBe(NESTED_SUBCOLLECTIONS.TUNE_SONGS);
  });

  it('TV_SHOWS maps to NESTED_SUBCOLLECTIONS.TV_SHOWS', () => {
    expect(COLLECTION_GROUPS.TV_SHOWS).toBe(NESTED_SUBCOLLECTIONS.TV_SHOWS);
  });

  it('CHANNEL_MESSAGES maps to NESTED_SUBCOLLECTIONS.CHANNEL_MESSAGES', () => {
    expect(COLLECTION_GROUPS.CHANNEL_MESSAGES).toBe(NESTED_SUBCOLLECTIONS.CHANNEL_MESSAGES);
  });

  it('APPLICATION_REPLIES maps to NESTED_SUBCOLLECTIONS.APPLICATION_REPLIES', () => {
    expect(COLLECTION_GROUPS.APPLICATION_REPLIES).toBe(NESTED_SUBCOLLECTIONS.APPLICATION_REPLIES);
  });

  it('SUBMITTED_REPLIES maps to NESTED_SUBCOLLECTIONS.SUBMITTED_REPLIES', () => {
    expect(COLLECTION_GROUPS.SUBMITTED_REPLIES).toBe(NESTED_SUBCOLLECTIONS.SUBMITTED_REPLIES);
  });

  it('CONVERSATION_MESSAGES maps to NESTED_SUBCOLLECTIONS.CONVERSATION_MESSAGES', () => {
    expect(COLLECTION_GROUPS.CONVERSATION_MESSAGES).toBe(NESTED_SUBCOLLECTIONS.CONVERSATION_MESSAGES);
  });

  it('INVITE_MESSAGES maps to NESTED_SUBCOLLECTIONS.INVITE_MESSAGES', () => {
    expect(COLLECTION_GROUPS.INVITE_MESSAGES).toBe(NESTED_SUBCOLLECTIONS.INVITE_MESSAGES);
  });

  it('TAGGED_SKILLS maps to NESTED_SUBCOLLECTIONS.TAGGED_SKILLS', () => {
    expect(COLLECTION_GROUPS.TAGGED_SKILLS).toBe(NESTED_SUBCOLLECTIONS.TAGGED_SKILLS);
  });

  it('USER_SUGGESTIONS maps to NESTED_SUBCOLLECTIONS.USER_SUGGESTIONS', () => {
    expect(COLLECTION_GROUPS.USER_SUGGESTIONS).toBe(NESTED_SUBCOLLECTIONS.USER_SUGGESTIONS);
  });

  it('has all expected keys', () => {
    const expectedKeys = [
      'PROFILE_SKILLS',
      'SOCIAL_POSTS',
      'LIBRARY_ITEMS',
      'TALE_CHAPTERS',
      'TUNE_SONGS',
      'TV_SHOWS',
      'CHANNEL_MESSAGES',
      'APPLICATION_REPLIES',
      'SUBMITTED_REPLIES',
      'CONVERSATION_MESSAGES',
      'INVITE_MESSAGES',
      'TAGGED_SKILLS',
      'USER_SUGGESTIONS',
    ];
    for (const key of expectedKeys) {
      expect(COLLECTION_GROUPS).toHaveProperty(key);
    }
  });
});
