import { describe, it, expect, beforeAll } from "vitest";
import { mkdtemp, writeFile, readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { inspectMedia } from "../src/inspection/inspect-media.js";
import { runCmd } from "../src/video/ffmpeg.js";

// REAL-TOOL regression matrix (canonical-upload-content-classification):
// deterministic tiny fixtures generated by the same required FFmpeg toolchain
// the runtime uses, inspected by the REAL ffprobe + sharp path (no injected
// deps). These pin the live defects the plan exists to kill:
//   - audio-only WebM (with adversarial payload bytes appended) → audio
//   - AAC-only `mp42` M4A → audio (brand never decides)
//   - Ogg/Theora → video (the audio-guard bypass regression)
//   - two-frame GIF → animated-image-frames (frame-zero-only is never clean)
//
// ffmpeg/ffprobe are REQUIRED local prerequisites (the app repo's CLAUDE.md
// mandates ffmpeg for the emulator) — absence FAILS with a clear message.
// Individual optional ENCODERS (theora) degrade to a skip with a console
// warning, since presence varies by build; the unit layer still covers the
// classification rule with injected streams.

let dir: string;
const have: Record<string, boolean> = {};

async function gen(name: string, args: string[]): Promise<boolean> {
  const out = path.join(dir, name);
  const r = await runCmd("ffmpeg", ["-hide_banner", "-y", ...args, out], { timeoutMs: 60_000 });
  if (r.code !== 0) {
    console.warn(`[inspect-fixtures] SKIP ${name} — encoder unavailable in this ffmpeg build`);
    return false;
  }
  return true;
}

beforeAll(async () => {
  try {
    const v = await runCmd("ffprobe", ["-version"], { timeoutMs: 10_000 });
    if (v.code !== 0) throw new Error("nonzero");
  } catch {
    throw new Error(
      "PREREQUISITE: ffmpeg/ffprobe must be on PATH for the inspector fixture tests (winget install ffmpeg — already required by the app repo).",
    );
  }
  dir = await mkdtemp(path.join(tmpdir(), "mpc-fixtures-"));
  have["audio-opus.webm"] = await gen("audio-opus.webm", ["-f", "lavfi", "-i", "sine=frequency=440:duration=1", "-c:a", "libopus"]);
  have["audio-mp42.m4a"] = await gen("audio-mp42.m4a", ["-f", "lavfi", "-i", "sine=frequency=440:duration=1", "-c:a", "aac", "-brand", "mp42"]);
  have["video-h264.mp4"] = await gen("video-h264.mp4", ["-f", "lavfi", "-i", "testsrc2=size=64x64:duration=1", "-f", "lavfi", "-i", "sine=frequency=440:duration=1", "-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac"]);
  have["video-theora.ogv"] = await gen("video-theora.ogv", ["-f", "lavfi", "-i", "testsrc2=size=64x64:duration=1", "-c:v", "libtheora", "-an", "-f", "ogg"]);
  have["audio-vorbis.ogg"] = await gen("audio-vorbis.ogg", ["-f", "lavfi", "-i", "sine=frequency=440:duration=1", "-c:a", "libvorbis", "-f", "ogg"]);
  have["anim.gif"] = await gen("anim.gif", ["-f", "lavfi", "-i", "testsrc2=size=32x24:duration=1:rate=2", "-frames:v", "2"]);
  have["still.png"] = await gen("still.png", ["-f", "lavfi", "-i", "testsrc2=size=32x24:duration=1", "-frames:v", "1"]);
}, 120_000);

function requireFixture(name: string): string {
  if (!have[name]) throw new Error(`fixture ${name} was not generated`);
  return path.join(dir, name);
}

describe("inspectMedia real-tool regressions", () => {
  it("audio-only WebM → definitive audio, audio-only plan (the intermittent-block regression)", async () => {
    const r = await inspectMedia({ localPath: requireFixture("audio-opus.webm") });
    expect(r.status).toBe("definitive");
    expect(r.canonicalKind).toBe("audio");
    expect(r.safetyPlan).toBe("audio-only");
    expect(r.streams.timedVideo).toBe(0);
    expect(r.codecs.audio).toEqual(["opus"]);
  });

  it("audio-only WebM with ADVERSARIAL trailing payload bytes (83 81 01) is still audio — payload bytes are never container metadata", async () => {
    const src = await readFile(requireFixture("audio-opus.webm"));
    const evil = path.join(dir, "audio-evil.webm");
    await writeFile(evil, Buffer.concat([src, Buffer.from([0x83, 0x81, 0x01, 0x83, 0x81, 0x01])]));
    const r = await inspectMedia({ localPath: evil });
    expect(r.canonicalKind).toBe("audio");
    expect(r.safetyPlan).toBe("audio-only");
  });

  it("AAC-only `mp42` M4A → audio (the deterministic Safari-audio regression; brand never decides)", async () => {
    const r = await inspectMedia({ localPath: requireFixture("audio-mp42.m4a") });
    expect(r.status).toBe("definitive");
    expect(r.canonicalKind).toBe("audio");
    expect(r.container).toBe("isobmff");
    expect(r.codecs.audio).toEqual(["aac"]);
  });

  it("H.264+AAC MP4 → video with video-frames plan", async () => {
    const r = await inspectMedia({ localPath: requireFixture("video-h264.mp4") });
    expect(r.canonicalKind).toBe("video");
    expect(r.safetyPlan).toBe("video-frames");
    expect(r.codecs.video).toEqual(["h264"]);
  });

  it("Ogg/Theora VIDEO → video-frames — the audio-guard bypass becomes impossible", async () => {
    if (!have["video-theora.ogv"]) return; // encoder-dependent; rule covered by the unit layer
    const r = await inspectMedia({ localPath: requireFixture("video-theora.ogv") });
    expect(r.canonicalKind).toBe("video");
    expect(r.safetyPlan).toBe("video-frames");
    expect(r.codecs.video).toEqual(["theora"]);
  });

  it("Ogg/Vorbis audio → audio (Ogg is probed, never blanket-audio)", async () => {
    if (!have["audio-vorbis.ogg"]) return;
    const r = await inspectMedia({ localPath: requireFixture("audio-vorbis.ogg") });
    expect(r.canonicalKind).toBe("audio");
    expect(r.safetyPlan).toBe("audio-only");
  });

  it("two-frame GIF → image with the animated-image-frames plan (never frame-zero-only clean)", async () => {
    const r = await inspectMedia({ localPath: requireFixture("anim.gif") });
    expect(r.canonicalKind).toBe("image");
    expect(r.safetyPlan).toBe("animated-image-frames");
    expect(r.streams.imageFrames).toBeGreaterThanOrEqual(2);
  });

  it("still PNG → image with the still-image plan, decoder-proven", async () => {
    const r = await inspectMedia({ localPath: requireFixture("still.png") });
    expect(r.canonicalKind).toBe("image");
    expect(r.safetyPlan).toBe("still-image");
    expect(r.streams.imageFrames).toBe(1);
  });
});
