// Collection group query constants
//
// Frontend: collectionGroup(db, COLLECTION_GROUPS.SOCIAL_POSTS)
// Backend:  db.collectionGroup(COLLECTION_GROUPS.SOCIAL_POSTS)

import { USER_SUBCOLLECTIONS, NESTED_SUBCOLLECTIONS } from './collections.js';

export const COLLECTION_GROUPS = {
  PROFILE_SKILLS: USER_SUBCOLLECTIONS.PROFILE_SKILLS,
  SOCIAL_POSTS: NESTED_SUBCOLLECTIONS.SOCIAL_POSTS,
  TALE_CHAPTERS: NESTED_SUBCOLLECTIONS.TALE_CHAPTERS,
  TUNE_TRACKS: NESTED_SUBCOLLECTIONS.TUNE_TRACKS,
  TELEVISION_EPISODES: NESTED_SUBCOLLECTIONS.TELEVISION_EPISODES,
  GUILD_CHAT_MESSAGES: NESTED_SUBCOLLECTIONS.GUILD_CHAT_MESSAGES,
  COMMISSION_PROPOSALS: NESTED_SUBCOLLECTIONS.COMMISSION_PROPOSALS,
  AUDITION_ENTRIES: NESTED_SUBCOLLECTIONS.AUDITION_ENTRIES,
  CONVERSATION_MESSAGES: NESTED_SUBCOLLECTIONS.CONVERSATION_MESSAGES,
  INVITE_MESSAGES: NESTED_SUBCOLLECTIONS.INVITE_MESSAGES,
  TAGGED_CRAFT_SKILLS: NESTED_SUBCOLLECTIONS.TAGGED_CRAFT_SKILLS,
  USER_SUGGESTIONS: NESTED_SUBCOLLECTIONS.USER_SUGGESTIONS,
} as const;
