// Collection group query constants
//
// Frontend: collectionGroup(db, COLLECTION_GROUPS.SOCIAL_POSTS)
// Backend:  db.collectionGroup(COLLECTION_GROUPS.SOCIAL_POSTS)

import { USER_SUBCOLLECTIONS, NESTED_SUBCOLLECTIONS } from './collections.js';

export const COLLECTION_GROUPS = {
  PROFILE_SKILLS: USER_SUBCOLLECTIONS.PROFILE_SKILLS,
  SOCIAL_POSTS: NESTED_SUBCOLLECTIONS.SOCIAL_POSTS,
  LIBRARY_ITEMS: NESTED_SUBCOLLECTIONS.LIBRARY_ITEMS,
  TALE_CHAPTERS: NESTED_SUBCOLLECTIONS.TALE_CHAPTERS,
  TUNE_SONGS: NESTED_SUBCOLLECTIONS.TUNE_SONGS,
  TV_SHOWS: NESTED_SUBCOLLECTIONS.TV_SHOWS,
  CHANNEL_MESSAGES: NESTED_SUBCOLLECTIONS.CHANNEL_MESSAGES,
  APPLICATION_REPLIES: NESTED_SUBCOLLECTIONS.APPLICATION_REPLIES,
  SUBMITTED_REPLIES: NESTED_SUBCOLLECTIONS.SUBMITTED_REPLIES,
  CONVERSATION_MESSAGES: NESTED_SUBCOLLECTIONS.CONVERSATION_MESSAGES,
  INVITE_MESSAGES: NESTED_SUBCOLLECTIONS.INVITE_MESSAGES,
  TAGGED_SKILLS: NESTED_SUBCOLLECTIONS.TAGGED_SKILLS,
  USER_SUGGESTIONS: NESTED_SUBCOLLECTIONS.USER_SUGGESTIONS,
} as const;
